# Generated by Django 4.1.3 on 2023-05-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('misId', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('year', models.CharField(max_length=70)),
                ('division', models.CharField(max_length=70)),
                ('department', models.CharField(max_length=70)),
                ('cgpa', models.CharField(max_length=70)),
                ('attendance', models.CharField(max_length=70)),
            ],
        ),
    ]
